steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["-c", "chmod 400 ./cloud_bundle_install.sh"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["bash", "./cloud_bundle_install.sh", "ssh ${_SERVER} && docker-compose up -d"]
    # args:
    #   [
    #     "run",
    #     "deploy",
    #     "${_SERVICE_NAME}",
    #     "--image",
    #     "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}",
    #     "--region",
    #     "asia-southeast1",
    #     "--platform",
    #     "managed",
    #     "--allow-unauthenticated",
    #   ]
